In [40]:
class MinMax:
    def __init__(self, game):
        self.game = game
        self.original_player = game.last_player()
        print(game.original_player)

    def min_max(self, game, is_max_player):
        if game.is_terminated():
            winner = game.get_winner()
            if winner == self.original_player:
                return None, 1
            elif winner == 0:
                return None, 0
            else:
                return None, -1

        if is_max_player:
            print("进入max递归")
            best_score = -float('inf')
            best_action = None
            for action in game.get_actions():
                new_game = game.clone()
                print("当前的action: ", action)
                new_game.move(action)
                print("当前进入递归的玩家： ", new_game.player)
                _, score = self.min_max(new_game, True)
                if score > best_score:
                    best_score = score
                    best_action = action
                print("max_player: ", new_game.player, "best_action: ", best_action, "best_score: ", best_score)
            return best_action, best_score
        else:
            print("进入min递归")
            best_score = float('inf')
            best_action = None
            for action in game.get_actions():
                new_game = game.clone()
                print("当前的action: ", action)
                new_game.move(action)
                print("当前递归的玩家： ", new_game.player)
                _, score = self.min_max(new_game, False)
                if score < best_score:
                    best_score = score
                    best_action = action
                print("min_player: ", new_game.player, "best_action: ", best_action, "best_score: ", best_score)
            return best_action, best_score

    def best_move(self):
        action, _ = self.min_max(self.game,  False)
        return action

In [41]:
from src import *

In [33]:
game = TicTacToe()
game.render()
game.move(0)
game.move(1)
game.move(7)
game.move(2)
game.move(8)
game.move(4)
game.render()
print("game player: ", game.player)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 1. -1. -1.]
 [ 0. -1.  0.]
 [ 0.  1.  1.]]
game player:  1


In [34]:
min_max_policy = MinMax(game)
best_move = min_max_policy.best_move()
print(best_move, 6)
game.move(best_move)
game.render()

当前的action:  3
当前进入递归的玩家：  -1
当前的action:  5
当前递归的玩家：  1
当前的action:  6
当前进入递归的玩家：  -1
max_player:  -1 best_action:  6 best_score:  1
min_player:  1 best_action:  5 best_score:  1
当前的action:  6
当前递归的玩家：  1
min_player:  1 best_action:  6 best_score:  -1
max_player:  -1 best_action:  3 best_score:  -1
当前的action:  5
当前进入递归的玩家：  -1
当前的action:  3
当前递归的玩家：  1
当前的action:  6
当前进入递归的玩家：  -1
max_player:  -1 best_action:  6 best_score:  1
min_player:  1 best_action:  3 best_score:  1
当前的action:  6
当前递归的玩家：  1
min_player:  1 best_action:  6 best_score:  -1
max_player:  -1 best_action:  3 best_score:  -1
当前的action:  6
当前进入递归的玩家：  -1
max_player:  -1 best_action:  6 best_score:  1
传进来的玩家:  1
6 6
[[ 1. -1. -1.]
 [ 0. -1.  0.]
 [ 1.  1.  1.]]


In [36]:
game = TicTacToe()
game.move(4)
min_max_policy = MinMax(game)
game.move(min_max_policy.best_move())

当前的action:  0
当前进入递归的玩家：  1
当前的action:  1
当前递归的玩家：  -1
当前的action:  2
当前进入递归的玩家：  1
当前的action:  3
当前递归的玩家：  -1
当前的action:  8
当前进入递归的玩家：  1
当前的action:  5
当前递归的玩家：  -1
min_player:  -1 best_action:  5 best_score:  -1
当前的action:  6
当前递归的玩家：  -1
当前的action:  5
当前进入递归的玩家：  1
max_player:  1 best_action:  5 best_score:  1
当前的action:  7
当前进入递归的玩家：  1
当前的action:  5
当前递归的玩家：  -1
min_player:  -1 best_action:  5 best_score:  -1
max_player:  1 best_action:  5 best_score:  1
min_player:  -1 best_action:  5 best_score:  -1
当前的action:  7
当前递归的玩家：  -1
min_player:  -1 best_action:  5 best_score:  -1
max_player:  1 best_action:  8 best_score:  -1
当前的action:  5
当前进入递归的玩家：  1
当前的action:  8
当前递归的玩家：  -1
当前的action:  6
当前进入递归的玩家：  1
当前的action:  7
当前递归的玩家：  -1
min_player:  -1 best_action:  7 best_score:  -1
max_player:  1 best_action:  6 best_score:  -1
当前的action:  7
当前进入递归的玩家：  1
当前的action:  6
当前递归的玩家：  -1
min_player:  -1 best_action:  6 best_score:  0
max_player:  1 best_action:  7 best_score:  0
min_player:  -

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [10]:
game.render()()

[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]


TypeError: 'NoneType' object is not callable

In [11]:
game.move(1)
game.move(min_max_policy.best_move())
game.render()

当前的action:  2
当前进入递归的玩家：  1
当前的action:  3
当前递归的玩家：  -1
当前的action:  8
当前进入递归的玩家：  1
当前的action:  5
当前递归的玩家：  -1
min_player:  -1 best_action:  5 best_score:  -1
当前的action:  6
当前递归的玩家：  -1
当前的action:  5
当前进入递归的玩家：  1
max_player:  1 best_action:  5 best_score:  1
当前的action:  7
当前进入递归的玩家：  1
当前的action:  5
当前递归的玩家：  -1
min_player:  -1 best_action:  5 best_score:  -1
max_player:  1 best_action:  5 best_score:  1
min_player:  -1 best_action:  5 best_score:  -1
当前的action:  7
当前递归的玩家：  -1
min_player:  -1 best_action:  5 best_score:  -1
max_player:  1 best_action:  8 best_score:  -1
当前的action:  5
当前进入递归的玩家：  1
当前的action:  8
当前递归的玩家：  -1
当前的action:  6
当前进入递归的玩家：  1
当前的action:  7
当前递归的玩家：  -1
min_player:  -1 best_action:  7 best_score:  -1
max_player:  1 best_action:  6 best_score:  -1
当前的action:  7
当前进入递归的玩家：  1
当前的action:  6
当前递归的玩家：  -1
min_player:  -1 best_action:  6 best_score:  0
max_player:  1 best_action:  7 best_score:  0
min_player:  -1 best_action:  8 best_score:  0
当前的action:  6
当前递归的玩家：

In [12]:
game.move(2)
game.move(min_max_policy.best_move())
game.render()

当前的action:  8
当前进入递归的玩家：  1
当前的action:  3
当前递归的玩家：  -1
当前的action:  5
当前进入递归的玩家：  1
当前的action:  6
当前递归的玩家：  -1
min_player:  -1 best_action:  6 best_score:  -1
max_player:  1 best_action:  5 best_score:  -1
当前的action:  6
当前进入递归的玩家：  1
max_player:  1 best_action:  6 best_score:  1
min_player:  -1 best_action:  3 best_score:  1
当前的action:  5
当前递归的玩家：  -1
当前的action:  3
当前进入递归的玩家：  1
当前的action:  6
当前递归的玩家：  -1
min_player:  -1 best_action:  6 best_score:  -1
max_player:  1 best_action:  3 best_score:  -1
当前的action:  6
当前进入递归的玩家：  1
max_player:  1 best_action:  6 best_score:  1
min_player:  -1 best_action:  3 best_score:  1
当前的action:  6
当前递归的玩家：  -1
min_player:  -1 best_action:  6 best_score:  -1
max_player:  1 best_action:  8 best_score:  -1
当前的action:  3
当前进入递归的玩家：  1
当前的action:  8
当前递归的玩家：  -1
当前的action:  5
当前进入递归的玩家：  1
当前的action:  6
当前递归的玩家：  -1
min_player:  -1 best_action:  6 best_score:  -1
max_player:  1 best_action:  5 best_score:  -1
当前的action:  6
当前进入递归的玩家：  1
max_player:  1 best_a

In [13]:
game.move(8)
game.move(min_max_policy.best_move())
game.render()

当前的action:  3
当前进入递归的玩家：  1
max_player:  1 best_action:  3 best_score:  1
当前的action:  5
当前进入递归的玩家：  1
当前的action:  3
当前递归的玩家：  -1
min_player:  -1 best_action:  3 best_score:  0
max_player:  1 best_action:  3 best_score:  1
传进来的玩家:  -1
[[-1.  1.  1.]
 [-1.  1.  0.]
 [-1. -1.  1.]]


In [42]:
game.reset()
game.move(0)
game.move(1)
game.move(7)
game.move(2)
game.move(8)
game.move(4)
game.render()

[[ 1. -1. -1.]
 [ 0. -1.  0.]
 [ 0.  1.  1.]]


In [43]:
min_max_policy_1 = MinMax(game)
game.move(min_max_policy_1.best_move())

当前的action:  3
当前进入递归的玩家：  -1
当前的action:  5
当前递归的玩家：  1
当前的action:  6
当前进入递归的玩家：  -1
max_player:  -1 best_action:  6 best_score:  1
min_player:  1 best_action:  5 best_score:  1
当前的action:  6
当前递归的玩家：  1
min_player:  1 best_action:  6 best_score:  -1
max_player:  -1 best_action:  3 best_score:  -1
当前的action:  5
当前进入递归的玩家：  -1
当前的action:  3
当前递归的玩家：  1
当前的action:  6
当前进入递归的玩家：  -1
max_player:  -1 best_action:  6 best_score:  1
min_player:  1 best_action:  3 best_score:  1
当前的action:  6
当前递归的玩家：  1
min_player:  1 best_action:  6 best_score:  -1
max_player:  -1 best_action:  3 best_score:  -1
当前的action:  6
当前进入递归的玩家：  -1
max_player:  -1 best_action:  6 best_score:  1
传进来的玩家:  1


In [44]:
game.render()

[[ 1. -1. -1.]
 [ 0. -1.  0.]
 [ 1.  1.  1.]]


In [3]:
import numpy as np
from copy import deepcopy
from typing import Callable, Optional


class TicTacToe(object):

    @classmethod
    def from_state(cls, state: tuple[int, ...], player: int):
        obj = TicTacToe()
        obj.board = np.array(state)
        obj.player = player
        return obj

    @classmethod
    def eval(cls, state, player):
        pass

    def __init__(self, start_player=1, default_state_formatter: Callable[[tuple[int, ...]], str] = str):
        self.board = np.zeros(9)
        self.player = start_player
        self.default_state_formatter = default_state_formatter

    def move(self, action):
        if self.board[action] != 0:
            raise Exception("Invalid move")
        self.board[action] = self.player
        self.player = -self.player

    def agent_move(self, policy):
        best_action = policy(self.get_state(), self.player, self.get_actions())
        self.move(best_action)
        return best_action

    def reset(self, start_player=1):
        self.board = np.zeros(9)
        self.player = start_player

    def render(self, state_formatter: Optional[Callable[[tuple[int, ...]], str]] = None):
        formatter = state_formatter or self.default_state_formatter
        print(formatter(self.get_state()), flush=True)

    def get_state(self) -> tuple[int, ...]:
        return tuple(self.board.astype(int).tolist())

    def get_actions(self):
        return set(np.where(self.board == 0)[0].tolist())

    def get_winner(self):
        board = self.board.reshape([3,3])

        for i in range(3):
            if abs(board[i].sum()) == 3:
                return board[i][0]
            if abs(board[:, i].sum()) == 3:
                return board[0][i]

        for j in range(3):
            if abs(board.diagonal().sum()) == 3:
                return board[0, 0]

            if abs(np.fliplr(board).diagonal().sum()) == 3:
                return int(board[0, 2])
        return 0

    def is_terminated(self):
        return not self.get_actions() or self.get_winner()

    def update_state(self, state, player):
        self.board = np.array(state, dtype=int)
        self.player = player

    def clone(self):
        return deepcopy(self)

    def last_player(self):
        return -self.player

In [4]:
ttt = TicTacToe()
        

In [6]:
state = ttt.get_state()


In [7]:
test_state = np.array(state).reshape(3, 3)

In [8]:
print(test_state)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
ttt.move(4)

In [11]:
print(test_state)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
ttt.render()

(0, 0, 0, 0, 1, 0, 0, 0, 0)


In [15]:
state =  ttt.get_state()
test_state = np.array(state).reshape(3, 3)
print(test_state)

[[0 0 0]
 [0 1 0]
 [0 0 0]]


In [16]:
ttt.get_actions()

{0, 1, 2, 3, 5, 6, 7, 8}

In [17]:
ttt.move(1)
ttt.render()

(0, -1, 0, 0, 1, 0, 0, 0, 0)


In [18]:
state =  ttt.get_state()
test_state = np.array(state).reshape(3, 3)
print(test_state)
ttt.get_actions()

[[ 0 -1  0]
 [ 0  1  0]
 [ 0  0  0]]


{0, 2, 3, 5, 6, 7, 8}

In [20]:
p1, p2, a1, a2 = 0, 0, 0, 0

lines = list(test_state[:]) + list(test_state.T[:]) + [np.diag(test_state)] + [np.diag(np.fliplr(test_state))]

print(lines)


[array([ 0, -1,  0]), array([0, 1, 0]), array([0, 0, 0]), array([0, 0, 0]), array([-1,  1,  0]), array([0, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]


In [26]:
def calculate_potential_wins(test_state):
    p1, p2, a1, a2 = 0, 0, 0, 0

    lines = list(test_state[:]) + list(test_state.T[:]) + [np.diag(test_state)] + [np.diag(np.fliplr(test_state))]

    for line in lines:
        unique, counts = np.unique(line, return_counts=True)
        
        counts_dict = dict(zip(unique, counts))

        if 1 in counts_dict and -1 not in counts_dict:
            if counts_dict[1] == 1:
                p1 += 1
            elif counts_dict[1] == 2:
                p2 += 1

        if -1 in counts_dict and 1 not in counts_dict:
            if counts_dict[-1] == 1:
                a1 += 1
            elif counts_dict[-1] == 2:
                a2 += 1
                
    return {'p1': p1, 'p2': p2, 'a1': a1, 'a2': a2}


In [27]:
calculated_wins = calculate_potential_wins(test_state)

In [28]:
calculated_wins['p1']

3

In [30]:
np.unique(np.array([1,1,1,2,3,2,3]), return_counts=True)

(array([1, 2, 3]), array([3, 2, 2]))

In [31]:
print(calculated_wins['p1'] + calculated_wins['p2'] * 3 - calculated_wins['a2'] * 3 - calculated_wins['a1'])

2


In [32]:
print(test_state)

[[ 0 -1  0]
 [ 0  1  0]
 [ 0  0  0]]


In [34]:
print(calculated_wins['p1'] + calculated_wins['p2'] * 3)

3


In [38]:
player = 1

In [35]:
state = (-1, -1, -1, 0, 0, 0, 1, 1, 1)

In [36]:
curr_state = np.array(state).reshape(3, 3)
curr_state

array([[-1, -1, -1],
       [ 0,  0,  0],
       [ 1,  1,  1]])

In [37]:
temp_state = curr_state.copy()
temp_state

array([[-1, -1, -1],
       [ 0,  0,  0],
       [ 1,  1,  1]])

In [39]:
temp_state == player

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [40]:
curr_state[temp_state == player]

array([1, 1, 1])

In [42]:
curr_state[temp_state == player] = 1
curr_state

array([[-1, -1, -1],
       [ 0,  0,  0],
       [ 1,  1,  1]])

In [44]:
(temp_state != player) & (temp_state != 0)

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [45]:
curr_state[(temp_state != player) & (temp_state != 0)] = -1
curr_state

array([[-1, -1, -1],
       [ 0,  0,  0],
       [ 1,  1,  1]])

In [91]:
from src.policies.q_policies.base_q_policy import BaseQPolicySingle
from src.heuristics import TicTacToeHeuristic
from src.tictactoe import TicTacToe


class MinMaxPolicy(BaseQPolicySingle):
    def __init__(self, game_cls, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.game_cls = game_cls
        self.heuristic = TicTacToeHeuristic()

    def min_max(self, game: TicTacToe, is_max_player, cloned_game, depth):
        if game.is_terminated() and depth <= 3:
            winner = game.get_winner()
            if winner == cloned_game.player:
                return 1
            elif winner == 0:
                return 0
            else:
                return -1
        if depth > 3 and not game.is_terminated:
            return self.heuristic(game.get_state(), cloned_game.player)

        best_score = -float('inf') if is_max_player else float('inf')
        for action in game.get_actions():
            new_game = game.clone()
            new_game.move(action)
            score = self.min_max(new_game, not is_max_player, cloned_game, depth+1)
            if (is_max_player and score > best_score) or (not is_max_player and score < best_score):
                best_score = score
        return best_score

    def get_all_Qs(self, state: tuple[int, ...], player: int, action_space: set[int]) -> dict[int, float]:
        q_values = {}
        for action in action_space:
            new_game = self.game_cls.from_state(state, player)
            cloned_game = new_game.clone()
            new_game.move(action)
            score = self.min_max(new_game, False, cloned_game, depth=0)
            q_values[action] = score
        return q_values

    def update_Q(self, state: tuple[int, ...], player: int, action: int, Q: float) -> None:
        raise NotImplementedError

import numpy as np
class TicTacToeHeuristic():
    def __init__(self):
        pass

    def __call__(self, state: tuple[int, ...], player: int) -> float:
        # p means current player
        # a means opponent player
        a1 = a2 = p1 = p2 = 0
        curr_state = np.array(state).reshape(3, 3)
        temp_state = curr_state.copy()

        curr_state[temp_state == player] = 1
        curr_state[(temp_state != player) & (temp_state != 0)] = -1

        lines = list(curr_state[:]) + list(curr_state.T[:]) + [np.diag(curr_state)] + [np.diag(np.fliplr(curr_state))]
        for line in lines:
            unique, counts = np.unique(line, return_counts=True)
            counts_dict = dict(zip(unique, counts))
            if 1 in counts_dict and -1 not in counts_dict:
                if counts_dict[1] == 1:
                    p1 += 1
                elif counts_dict[1] == 2:
                    p2 += 1
            if -1 in counts_dict and 1 in counts_dict:
                if counts_dict[-1] == 1:
                    a1 += 1
                elif counts_dict[-1] == 2:
                    a2 += 1

        scores = {'p1': p1, 'p2': p2, 'a1': a1, 'a2': a2}

        return scores['p1'] + scores['p2'] * 3 - scores['a2'] * 3 - scores['a1']

In [92]:
ttt = TicTacToe()
ttt.render()

(0, 0, 0, 0, 0, 0, 0, 0, 0)


In [93]:
ttt.move(4)
ttt.move(0)
ttt.render()

(-1, 0, 0, 0, 1, 0, 0, 0, 0)


In [94]:
test_min_max = MinMaxPolicy(game_cls=ttt)

In [98]:
scores = test_min_max.get_all_Qs(ttt.get_state(), ttt.player, ttt.get_actions())
scores

{1: inf, 2: 1, 3: inf, 5: 1, 6: 1, 7: 1, 8: inf}

In [101]:
ttt.reset()
ttt.render()

(0, 0, 0, 0, 0, 0, 0, 0, 0)


In [102]:
ttt.move(4)
ttt.move(0)
ttt.render()

(-1, 0, 0, 0, 1, 0, 0, 0, 0)


In [103]:
test_min_max = MinMaxPolicy(game_cls=ttt)
scores = test_min_max.get_all_Qs(ttt.get_state(), ttt.player, ttt.get_actions())
scores

{1: inf, 2: 1, 3: inf, 5: 1, 6: 1, 7: 1, 8: inf}

In [105]:
ttt.move(1)
ttt.render()

(-1, 1, 0, 0, 1, 0, 0, 0, 0)


In [109]:
test_min_max = MinMaxPolicy(game_cls=ttt)
print(ttt.get_state())
print(ttt.get_actions())
print(ttt.player)
scores = test_min_max.get_all_Qs(ttt.get_state(), ttt.player, ttt.get_actions())
scores

(-1, 1, 0, 0, 1, 0, 0, 0, 0)
{2, 3, 5, 6, 7, 8}
-1


{2: -inf, 3: -inf, 5: -inf, 6: -inf, 7: -inf, 8: -inf}

ttt.move(7)
ttt.render()

In [110]:
ttt.move(7)
ttt.render()

(-1, 1, 0, 0, 1, 0, 0, -1, 0)


In [111]:
test_min_max = MinMaxPolicy(game_cls=ttt)
scores = test_min_max.get_all_Qs(ttt.get_state(), ttt.player, ttt.get_actions())
scores

{2: -1, 3: inf, 5: 1, 6: inf, 8: inf}